[[language]]
# https://github.com/helix-editor/helix/discussions/10665
name = "gotmpl"
file-types = ["gohtml"]
language-servers = ["gopls", "vscode-html-language-server"]

[[language]]
name = "ini"
file-types = ["ini", { glob = ".aws/config" }, { glob = ".aws/credentials" }]

[[language]]
name = "sshclientconfig"
file-types = ["sshclientconfig", { glob = ".ssh/config" }, { glob =".ssh/config.d/*" }]
